replaced TestGame entries with gameLoop() at new game and continue event (#18)
* replaced TestGame entries with gameLoop() at new game and continue event

* replaces "continue" with "new game" in settings for clarity on what the action does

In the event of calling a new game from the pause screen by pressing N and when calling to continue from settings by pressing P the code had a line :
TestGame().run()

where TestGame does not exist and perhaps was a placeholder meant to stay during the dev phase only.
I have replaced it with gameLoop() which starts a new game

when calling new game it makes sense to start a new game
and when calling from settings to continue, we know that a game is not being continued so starting a new game works.

The following was the error displayed in the console.

Traceback (most recent call last):
   File "/home/user/git/ballbrick/game.py", line 584, in run
     gameLoop()
   File "/home/user/git/ballbrick/game.py", line 494, in gameLoop
     paused()
   File "/home/user/git/ballbrick/game.py", line 411, in paused
     TestGame().run()
NameError: name 'TestGame' is not defined